<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup>
<OutputType>WinExe</OutputType><TargetFramework>net10.0-windows</TargetFramework><UseWindowsForms>true</UseWindowsForms>
<AssemblyName>FileListToExcel</AssemblyName><ApplicationIcon>app.ico</ApplicationIcon><ApplicationManifest>app.manifest</ApplicationManifest>
<ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode><PublishTrimmed>false</PublishTrimmed><DebugType>embedded</DebugType>
</PropertyGroup><ItemGroup><ProjectReference Include="../FileListToExcel.Core/FileListToExcel.Core.csproj" /></ItemGroup></Project>
